window.LDTT_TRAINER_ROSTER = [
  {
    "id": "fred-harris",
    "slug": "fred-harris",
    "pageSlug": "fredharris",
    "name": "Fred Harris",
    "state": "California",
    "market": "San Diego, CA",
    "serviceArea": "San Diego and surrounding California communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Frederick brings strong people skills, discipline, and a service mindset to dog training after years in hospitality and nonprofit work supporting foster youth.",
    "fullBio": "Frederick Harris was born in Puerto Vallarta, Jalisco, and raised in Sayulita before relocating to San Diego at the age of 10, where he continues to reside today. His diverse background and life experiences have shaped a strong passion for personal growth, service, and helping others succeed. Frederick discovered Lorenzo’s Dog Training Team through Carolina, a trainer that holds the position of Team Coordinator with the company, whom he met at a gym and who introduced him to the program. At a point in his life where he was actively seeking meaningful change and a way to positively impact others, dog training stood out as the perfect combination of purpose, discipline, and service. With a strong foundation in working with people, Frederick brings years of experience from the restaurant industry, where he has worked since the age of 16, as well as volunteer work with a nonprofit supporting foster youth. These roles helped him develop patience, leadership, communication skills, and the ability to adapt to different personalities — all essential qualities in effective dog training. Frederick’s goals are simple but powerful: to grow better each year and help those around him do the same. He is deeply committed to personal development and believes that training dogs is just as much about guiding people toward confidence, clarity, and consistency. Outside of dog training, Frederick enjoys weightlifting, martial arts, combat sports, and spending quality time with loved ones. His active lifestyle, disciplined mindset, and genuine desire to help others make him a valuable addition to the Lorenzo’s Dog Training Team.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/fred-harris",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/fred-harris.jpg",
    "photo": "/assets/trainer-bio-photos/fred-harris.jpg",
    "cardPhoto": "/assets/trainer-headshots/Frederick Harris TT 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in San Diego, CA | Fred Harris | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Fred Harris in San Diego, CA, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "genevieve-twilla",
    "slug": "genevieve-twilla",
    "pageSlug": "genevievetwilla",
    "name": "Genevieve Twilla",
    "state": "California",
    "market": "North Park, CA",
    "serviceArea": "North Park and surrounding California communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Genevieve “Skylar” Twilla combines lifelong animal passion with service-industry communication skills to help families build confidence and consistency.",
    "fullBio": "Born in San Diego and raised in Chula Vista, California, Genevieve “Skylar” Twilla now calls North Park home. With a lifelong love for animals and a genuine passion for helping others, Skylar brings enthusiasm, compassion, and dedication to every dog and family she works with. Skylar's journey into professional dog training began through a friend who introduced her to Lorenzo's Dog Training Team. Already passionate about animals, she was drawn to the opportunity to make a meaningful difference in the lives of dogs and their owners. Through Lorenzo's proven training methods and philosophy, Skylar found a way to help dogs achieve greater success while giving owners the tools and confidence needed to build stronger relationships with their pets. Having spent her entire career working in the service industry, Skylar has developed exceptional communication and people skills. Her experience working with individuals from all walks of life allows her to connect with clients, understand their unique challenges, and guide them through the training process with patience and encouragement. Combined with her love for dogs, this background helps her create positive and rewarding experiences for both dogs and their families. As a trainer, Skylar is driven by a simple but powerful mission: to help as many dogs and people as possible. She is committed to improving the lives of the families she serves, continuing her education, and expanding her understanding of canine behavior, personality differences, and effective training techniques. Her goal is not only to help dogs become well-mannered companions but also to empower owners with the knowledge and skills they need for long-term success. Outside of training, Skylar enjoys spending time outdoors, hiking with her dog, drawing, staying active, and working out. Her active lifestyle and appreciation for the outdoors reflect the same energy and dedication she brings to her work as a dog trainer. With a passion for animals, a heart for helping people, and a commitment to continuous growth, Skylar is proud to be part of Lorenzo's Dog Training Team and looks forward to helping dogs and their owners achieve lasting success together.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/genevieve-twilla",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/genevieve-twilla.jpg",
    "photo": "/assets/trainer-bio-photos/genevieve-twilla.jpg",
    "cardPhoto": "/assets/trainer-headshots/Genevieve Twilla 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in North Park, CA | Genevieve Twilla | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Genevieve Twilla in North Park, CA, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "daniel-bainbridge",
    "slug": "daniel-bainbridge",
    "pageSlug": "danielbainbridge",
    "name": "Daniel “Deuce” Bainbridge",
    "state": "Florida",
    "market": "Crestview, FL",
    "serviceArea": "Crestview and surrounding Florida communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Daniel, known as Deuce, brings hands-on discipline and a goal of becoming a leading Gulf Coast trainer through the LDTT system.",
    "fullBio": "Daniel Bainbridge CRESTVIEW, FL Daniel Bainbridge, better known as Deuce, was born in Nevada, but while growing up with parents in the military, he called a lot of places home. Some of those states include Colorado, Alaska, Indiana, Arizona, and California. Pensacola, Florida is where he currently lives. While seeking advice from his friend, Shavon Striggles, also an LDTT trainer, Shavon noticed Daniel’s natural talent in working with dogs. Wanting to give him the same opportunity he’d been given, Shavon told him that he should consider becoming a trainer with the team too. He jumped at the offer and the rest is LDTT history. When asked why he wanted to train with Lorenzo’s, Daniel said, “Because I am given an opportunity to help dogs and families, as well as feel supported and be given mentorship that I have never received from another company.” His goal is to become THE trainer of the Gulf Coast using the LDTT system to train, save, and educate the public. When he’s not working, Daniel enjoys riding motorcycles, playing combat sports, working with wood, and any other activity that allows him to work with his hands.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/daniel-bainbridge",
    "layout": "mock-5",
    "pageStatus": "Published",
    "locked": true,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/daniel-bainbridge.jpg",
    "photo": "/assets/trainer-bio-photos/daniel-bainbridge.jpg",
    "cardPhoto": "/assets/trainer-headshots/Daniel Bainbridge_RD 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Crestview, FL | Daniel “Deuce” Bainbridge | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Daniel “Deuce” Bainbridge in Crestview, FL, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Crestview Dog Owner",
    "review1Copy": "Daniel brought calm, hands-on direction to every session and showed us how to reinforce the training consistently at home.",
    "review2Author": "Gulf Coast Family",
    "review2Copy": "Deuce explained the reason behind each step, gave us practical tools, and helped our dog make progress we could see in daily life.",
    "review3Author": "Local Client",
    "review3Copy": "Daniel was patient with both our dog and our family. His clear coaching gave us more confidence, control, and a stronger routine.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "victoria-bayleigh-morris",
    "slug": "victoria-bayleigh-morris",
    "pageSlug": "victoriabayleighmorris",
    "name": "Victoria Bayleigh Morris",
    "state": "Florida",
    "market": "Milton, FL",
    "serviceArea": "Milton and surrounding Florida communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Bayleigh's veterinary technician background and love of animals led her into LDTT training after seeing what professional structure could do.",
    "fullBio": "Victoria Bayleigh Morris Victoria Bayleigh Morris was born in Ohio and currently resides in Milton, Florida. Her love of animals brought her to become a veterinary technician at a vet clinic, where she met one of LDTT’s trainers during a Lunch and Learn. While watching the trainer work their dog, she saw what a well-trained dog could really do, and she discovered her own dog’s capabilities in the attention and respect he demonstrated. Her thoughts then turned to wanting that for herself. She contacted LDTT and was one of the first to experience our new learning platform of online training. Her goals are for her dog, Neagan, to be her “right hand man” and to be able to work for herself. In her time away from training, Bayleigh likes to ride her motorcycle and spend time on the water.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/victoria-bayleigh-morris",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/victoria-bayleigh-morris.jpg",
    "photo": "/assets/trainer-bio-photos/victoria-bayleigh-morris.jpg",
    "cardPhoto": "/assets/trainer-headshots/Victoria Morris ETT 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Milton, FL | Victoria Bayleigh Morris | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Victoria Bayleigh Morris in Milton, FL, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "michael-king",
    "slug": "michael-king",
    "pageSlug": "michaelking",
    "name": "Michael King",
    "state": "Florida",
    "market": "Navarre, FL",
    "serviceArea": "Navarre and surrounding Florida communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Michael combines Air Force service, people skills, and personal experience with an aggressive dog to help families achieve better results.",
    "fullBio": "Michael King Navarre, Florida In his youth, Michael King moved around a bit, going from California to Arizona, then finally landing in Navarre, Florida, where he presently resides. In his life, he’s informally trained many dogs to do basic commands and learned how to work with people while in the service industry. He also served in the Air Force! Michael found out about Lorenzo’s when a friend referred him to an LDTT trainer, who helped him with his aggressive dog, Odin. When asked why he wanted to become a dog trainer, he said, “…because it would give me the opportunity to run a business, as well as be able to save and help as many dogs as I can. There’s nothing more that I want than to be able to run a business, play with dogs, and love doing it all at the same time.” When Michael isn’t training dogs, he enjoys playing guitar, video games, hiking, kayaking, fishing, and camping.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/michael-king",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/michael-king.jpg",
    "photo": "/assets/trainer-bio-photos/michael-king.jpg",
    "cardPhoto": "/assets/trainer-headshots/Michael King_TC 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Navarre, FL | Michael King | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Michael King in Navarre, FL, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "clark-patton",
    "slug": "clark-patton",
    "pageSlug": "clarkpatton",
    "name": "Clark Patton",
    "state": "Florida",
    "market": "Pensacola, FL",
    "serviceArea": "Pensacola and surrounding Florida communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Clark brings real estate, marketing, and client-service experience to dog training, with a focus on building reliable dogs and confident owners.",
    "fullBio": "Clark Patton Clark Patton was born and raised in Louisiana and now makes his home in Pensacola, Florida. When one of our LDTT trainers did a Lunch and Learn at his local vet clinic, Clark decided to sign his own dog up to help with a slight aggression issue. He was amazed at what the trainer was able to accomplish just in the evaluation. “It was like he was dancing and having so much fun. It made me realize that I could do the same thing.” Having been a real estate agent for two years, his experience working with people and marketing his services has been enjoyable for Clark, not to mention perfect for becoming a dog trainer. When we asked Clark about his goals, he said, “I want to create a business that has the ability to run itself so I can achieve the ultimate goal, having control over my time.” In his spare time, he enjoys reading, lifting weights, running 5ks, and pushing his friends to achieve their next fitness level.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/clark-patton",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/clark-patton.jpg",
    "photo": "/assets/trainer-bio-photos/clark-patton.jpg",
    "cardPhoto": "/assets/trainer-headshots/Clark Patton ETT 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Pensacola, FL | Clark Patton | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Clark Patton in Pensacola, FL, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "shavon-striggles",
    "slug": "shavon-striggles",
    "pageSlug": "shavonstriggles",
    "name": "Shavon Striggles",
    "state": "Georgia",
    "market": "Atlanta, GA",
    "serviceArea": "Atlanta and surrounding Georgia communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "Serious training. Serious results.",
    "bio": "Shavon grew up around dogs and is driven by changing the way people understand misunderstood breeds and canine relationships.",
    "fullBio": "Shavon Striggles Shavon was born and raised in Ft. Lauderdale, Florida. As a young child, Shavon was introduced to breeding Pit Bulls. He had the job of cleaning the kennels and feeding the dogs and so, Shavon fell in love with the breed. Over the years he noticed that Pit Bulls were developing a bad reputation. He began looking for ways to positively impact the way people perceived the breed. Shavon felt he had found a way to achieve this after learning from a friend about Lorenzo's Dog Training Team. He applied with the company to be a trainer and the rest is history! Meeting and working with Lorenzo has completely changed Shavon's outlook on the relationship between people and their canine companions. His goal is to see the number of deaths and abandoned dogs drop across the nation and says he now has a clear understanding on how he can contribute and achieve this goal. Shavon invisions himself growing with the company and making sure we have trainers globally. Aside from training dogs, Shavon's hobbies are drawing, dancing, and riding motorcycles.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/shavon-striggles",
    "layout": "mock-3",
    "pageStatus": "Published",
    "locked": true,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/shavon-striggles.jpg",
    "photo": "/assets/trainer-bio-photos/shavon-striggles.jpg",
    "cardPhoto": "/assets/trainer-headshots/Shavon Striggles RD 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Atlanta, GA | Shavon Striggles | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Shavon Striggles in Atlanta, GA, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Atlanta Dog Owner",
    "review1Copy": "Shavon helped us understand our dog's behavior and gave us a clear structure that made training easier to carry into everyday life.",
    "review2Author": "Atlanta Family",
    "review2Copy": "Shavon's calm leadership and commitment to misunderstood breeds gave us confidence and helped our dog become more focused at home and in public.",
    "review3Author": "Local Client",
    "review3Copy": "Shavon took time to explain each step, worked with us as owners, and helped create a more balanced relationship with our dog.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "christopher-almonte",
    "slug": "christopher-almonte",
    "pageSlug": "christopheralmonte",
    "name": "Christopher Almonte",
    "state": "Georgia",
    "market": "Atlanta, GA",
    "serviceArea": "Atlanta and surrounding Georgia communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Christopher's breeder background and powerful LDTT evaluation experience pushed him toward professional training and family impact.",
    "fullBio": "Christopher Almonte Atlanta, GA Christopher Almonte, originally from Miami, Florida, and currently based in Loganville, Georgia, is a passionate dog breeder and aspiring professional dog trainer with Lorenzo’s Dog Training Team. With a lifelong connection to dogs, Christopher’s experience began early in life and evolved into a dedicated pursuit through his work as a breeder. His interest in formal dog training was sparked after witnessing a powerful in-home evaluation with Blu from LDTT, where his 9-month-old XL Bully responded with remarkable obedience in just minutes. That moment ignited a commitment to not only strengthen his understanding of canine behavior but to make a lasting impact on families and their pets through structured training. Christopher's long-term goals include becoming one of the highest earners on the LDTT team and ultimately achieving financial success that allows him to retire his mother. His dedication, leadership mindset, and passion for dogs continue to drive his journey forward. In his free time, Christopher enjoys fitness training and gaming—two activities that reflect his focus, discipline, and love for growth.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/christopher-almonte",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/christopher-almonte.jpg",
    "photo": "/assets/trainer-bio-photos/christopher-almonte.jpg",
    "cardPhoto": "/assets/trainer-headshots/Christopher Almonte 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Atlanta, GA | Christopher Almonte | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Christopher Almonte in Atlanta, GA, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "aryson-whorley",
    "slug": "aryson-whorley",
    "pageSlug": "arysonwhorley",
    "name": "Aryson Whorley",
    "state": "Georgia",
    "market": "Atlanta, GA",
    "serviceArea": "Atlanta and surrounding Georgia communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Aryson brings veterinary clinic and dog daycare experience, plus a passion for helping owners see what training can change.",
    "fullBio": "Born in Hiroshima, Japan, and raised in Adel, Georgia, Aryson Whorley brings a unique perspective, strong work ethic, and genuine passion for helping both dogs and their owners succeed. Now based in the Atlanta, Georgia area, Aryson is dedicated to building stronger relationships between people and their canine companions through effective training and clear communication. Aryson's journey into professional dog training began after discovering Lorenzo's Dog Training Team through an Instagram reel. After becoming a client and learning more about the organization's mission and training philosophy, Aryson quickly developed a deep appreciation for the impact that quality dog training can have on families and their pets. Inspired by the results and the purpose behind the program, joining Lorenzo's Dog Training Team became a natural next step. Prior to becoming a trainer, Aryson gained valuable hands-on experience working in veterinary clinics and dog daycare environments. These experiences provided extensive exposure to canine behavior, animal care, and client interaction, helping to develop the skills necessary to work effectively with dogs of all ages, breeds, and temperaments. Aryson's passion for training is rooted in a desire to help people—especially those who may not even realize how much a well-trained dog can improve their daily lives. Whether helping owners overcome behavioral challenges, build confidence in their dogs, or strengthen the bond they share, Aryson is committed to creating positive and lasting results. Outside of dog training, Aryson enjoys drawing, writing music, and exploring the scientific principles that shape the world around us. This combination of creativity and curiosity contributes to a thoughtful, analytical approach to both training and problem-solving. With a passion for education, a background in animal care, and a commitment to helping both dogs and their owners thrive, Aryson is proud to be a part of Lorenzo's Dog Training Team and looks forward to making a positive difference in every family served.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/aryson-whorley",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/aryson-whorley.jpg",
    "photo": "/assets/trainer-bio-photos/aryson-whorley.jpg",
    "cardPhoto": "/assets/trainer-headshots/Aryson Whorley 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Atlanta, GA | Aryson Whorley | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Aryson Whorley in Atlanta, GA, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "robert-wesling",
    "slug": "robert-wesling",
    "pageSlug": "robertwesling",
    "name": "Robert Wesling",
    "state": "Georgia",
    "market": "Atlanta, GA",
    "serviceArea": "Atlanta and surrounding Georgia communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Robert became passionate about LDTT after training his own dog, Leia, and now helps owners build stronger relationships with their dogs.",
    "fullBio": "Robert Wesling ATLANTA, GA Robert Wesling was born in St. Louis, Missouri and now resides in Sandy Springs, Georgia. Dogs have always been a part of his life, but it wasn’t until he started training his own dog, Leia, that Robert realized he could only take her training so far on his own. Then, on a recommendation from his Veterinarian, Robert contacted Lorenzo’s and he officially became a client. “After finishing my training, I was hooked, and I knew I had to follow this passion for training dogs and helping people. I look forward to continuing my education in the art of dog training through the amazing mentors here at LDTT.” Having goals is important and Robert has a few. He’d love to buy a few acres of land, overlooking some mountains, with a small house to nap in and lots of dogs. When he’s not working, he likes to take long road trips with his dog, Leia. He also enjoys going hiking in national forests, he likes every type of barbeque, baseball, soccer, deep sea fishing, rollercoasters, and theme parks.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/robert-wesling",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/robert-wesling.jpg",
    "photo": "/assets/trainer-bio-photos/robert-wesling.jpg",
    "cardPhoto": "/assets/trainer-headshots/Robert Wesling  TC 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Atlanta, GA | Robert Wesling | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Robert Wesling in Atlanta, GA, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "chloe-chislom",
    "slug": "chloe-chislom",
    "pageSlug": "chloechislom",
    "name": "Chloe Chisolm",
    "state": "Georgia",
    "market": "Atlanta, GA",
    "serviceArea": "Atlanta and surrounding Georgia communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Chloe's veterinary technician background and shelter experience shaped her mission to help save dogs through effective, compassionate training.",
    "fullBio": "Chloe Chislom Atlanta, GA Born and raised in Atlanta, Georgia, Chloe Chisolm has dedicated her life to caring for animals. With a background as a veterinary technician, Chloe witnessed firsthand how misunderstood behavior issues can lead to heartbreaking outcomes. That experience ignited a powerful mission: to help save dogs through effective, compassionate training. Chloe discovered Lorenzo’s Dog Training Team during a lunch-and-learn session while working at a veterinary clinic and was immediately drawn to the team’s transformative approach. With years of hands-on experience—from volunteering in shelters to pet sitting and beyond—she now channels her passion into helping dogs thrive and stay in their forever homes. In her free time, Chloe enjoys hiking and creating digital art. Whether she’s exploring the outdoors or crafting something new, her creativity and empathy shine through in everything she does—especially her work with dogs and their families.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/chloe-chislom",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/chloe-chislom.jpg",
    "photo": "/assets/trainer-bio-photos/chloe-chislom.jpg",
    "cardPhoto": "/assets/trainer-headshots/Chloe Chisolm TT 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Atlanta, GA | Chloe Chisolm | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Chloe Chisolm in Atlanta, GA, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "jasmine-bland",
    "slug": "jasmine-bland",
    "pageSlug": "jasminebland",
    "name": "Jasmine Bland",
    "state": "Indiana",
    "market": "Hammond, IN",
    "serviceArea": "Hammond and surrounding Indiana communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Jasmine draws from veterinary technology education and a balanced-training mindset to serve owners and dogs in Indiana.",
    "fullBio": "Jasmine Bland Hammond, Indiana Jasmine Bland is originally from Illinois but now resides in Indiana. After seeing dog training classes going on, she knew she could do better than that, so she began a quest to find a balanced dog training program. She eventually came across Lorenzo’s and was eager to jump right in and begin her career. With two years of veterinarian technology school under her belt, Jasmine pulls from her education to better serve her dog training clients. Her goals are simple, she’d like to take care of her mom and buy a new car. When she’s not training, she enjoys reading and studying. To decompress after a long day, Jasmine listens to music and plays video games.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/jasmine-bland",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/jasmine-bland.jpg",
    "photo": "/assets/trainer-bio-photos/jasmine-bland.jpg",
    "cardPhoto": "/assets/trainer-headshots/Jasmine Bland 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Hammond, IN | Jasmine Bland | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Jasmine Bland in Hammond, IN, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "bailey-brown",
    "slug": "bailey-brown",
    "pageSlug": "baileybrown",
    "name": "Bailey Brown",
    "state": "Kentucky",
    "market": "Versailles, KY",
    "serviceArea": "Versailles and surrounding Kentucky communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Bailey became a trainer after LDTT helped her own dog, and now helps families learn to love and lead their dogs again.",
    "fullBio": "Bailey Brown Versailles, KY Bailey Brown is originally from Lexington, Kentucky, and now makes her home in Versailles, KY. She knew she needed help with the behavior of her own dog, so she sought the help of an LDTT trainer. Impressed with the progress they made, she decided to jump on board and become a trainer herself. “I wanted to help other people learn to love their dogs again. I really struggled with my dog before she was trained by LDTT and now we are a great team. I love training animals! I got my first dog when I was 2 and my first horse when I was 7. Working with animals has always been a love of mine and always will be.” When she’s not training, Bailey enjoys horseback riding, hiking, fishing, playing video games, and spending time with her family.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/bailey-brown",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/bailey-brown.jpg",
    "photo": "/assets/trainer-bio-photos/bailey-brown.jpg",
    "cardPhoto": "/assets/trainer-headshots/Bailey Brown ETT 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Versailles, KY | Bailey Brown | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Bailey Brown in Versailles, KY, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "emilio-marotta",
    "slug": "emilio-marotta",
    "pageSlug": "emiliomarotta",
    "name": "Emilio Marotta",
    "state": "Massachusetts",
    "market": "Boston, MA",
    "serviceArea": "Boston and surrounding Massachusetts communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Emilio is a former Marine, college athlete, Master Trainer, and dog lover focused on building trainers and helping more families.",
    "fullBio": "Emilo Marotta Although Emilio is originally from Boston, he’s now a 20-year resident of San Diego. He worked for many years in the financial and sales industries but felt that he didn't receive the rewards that he gains from working with man's best friend on a daily basis. Emilio is a former Marine and college athlete, as well as an avid dog lover. He was immediately drawn to training and working with pets and their owners, helping to improve their relationships. Emilio has spent the majority of his time helping people in San Diego in these very circumstances. He’s also worked with several rescue organizations, helping to rehabilitate many pups throughout San Diego County. \"It's a great feeling knowing I am helping people shape the pet they always wanted,\" he said. As Emilio has grown into his position, he’s finding his role in Lorenzo’s Dog Training Team is evolving as well. He’s growing his presence in San Diego by building and mentoring his team as a Master Trainer. He went on to say, “This gives me the opportunity to provide and pass on to other trainers what I received from Lorenzo and my fellow trainers. Plus, the impact on San Diego will be huge. This will allow us to reach more families and their dogs throughout the county and that’s the bottom line. Helping as many families, dogs, and individuals grow in this company is my mission”. Whenever he's not training dogs or helping people, Emilio spends his time with his family, which includes his beautiful wife, Trina, and his two Rottweilers, Sofia and Champ, and Rocco, a Pit Bull mix.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/emilio-marotta",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/emilio-marotta.jpg",
    "photo": "/assets/trainer-bio-photos/emilio-marotta.jpg",
    "cardPhoto": "/assets/trainer-headshots/Emilio Marotta 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Boston, MA | Emilio Marotta | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Emilio Marotta in Boston, MA, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "dylan-atkinson",
    "slug": "dylan-atkinson",
    "pageSlug": "dylanatkinson",
    "name": "Dylan Atkinson",
    "state": "Michigan",
    "market": "Ann Arbor, MI",
    "serviceArea": "Ann Arbor and surrounding Michigan communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Dylan brings lifelong dog experience, sales, and customer service skills to help owners understand dogs and the LDTT method.",
    "fullBio": "Dylan Atkinson Ann Arbor, Michigan Dylan Atkinson was born in Nevada and currently resides in Whitmore, Michigan. He grew up always having dogs in his life and his father even taught him how to train them. When Dylan realized his passion for dogs would also make a great career, the hunt was on to find a place to formally train him. That’s when he found Lorenzo’s. With a background in sales and customer service, Dylan is confident in his ability to work with all types of people, helping them understand LDTT training methods and why dogs do what they do. Dylan’s goals are to be his own boss, have financial freedom, gain generational wealth, and live a limitless life of happiness, doing what he loves. When he’s not training dogs, Dylan enjoys riding his ATV, playing video games, watching anime, and traveling the world.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/dylan-atkinson",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/dylan-atkinson.jpg",
    "photo": "/assets/trainer-bio-photos/dylan-atkinson.jpg",
    "cardPhoto": "/assets/trainer-headshots/Dylan Atkinson 360_x_360 ETT.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Ann Arbor, MI | Dylan Atkinson | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Dylan Atkinson in Ann Arbor, MI, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "tristan-gray",
    "slug": "tristan-gray",
    "pageSlug": "tristangray",
    "name": "Tristan Gray",
    "state": "New Hampshire",
    "market": "Durham, NH",
    "serviceArea": "Durham and surrounding New Hampshire communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Tristan became inspired after seeing his own dog Sophie's progress and is committed to helping as many dogs as possible.",
    "fullBio": "Tristan Gray Durham, New Hampshire Tristan Gray grew up in Montana and currently resides in Durham, New Hampshire. In his quest to have his dog, Sophie, professionally trained, he found Lorenzo’s Dog Training Team. He was amazed at Sophie’s progress, so much so that the thought of becoming a dog trainer himself was becoming clearer a clearer. He shadowed Sophie’s trainer and was amazed at the positive response he would get from his clients. Despite his family’s hesitance and hopes that he’d get a “real job”, Tristan learned about the training program at LDTT at an event, and he knew it was the chance of a lifetime, so he pushed forward and dove, headfirst, into becoming a dog trainer. When asked about his goals, Tristan responded, “I want to help as many dogs as I can. It is the most important thing to me as a dog trainer. It saddens me, the number of dogs currently in shelters. I want to volunteer and help train dogs that would otherwise not be adopted. They are man’s best friend for a reason. They just need a little guidance, and they can live their best life with their owner.” In his spare time, Tristan enjoys renovating and landscaping his home. He likes working on his sports car and, of course, driving it. Watching tv, playing video games, going on hikes and being outside, fly fishing, operating his drone, and using his degree in electronics are just a few of the things he likes to do.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/tristan-gray",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/tristan-gray.jpg",
    "photo": "/assets/trainer-bio-photos/tristan-gray.jpg",
    "cardPhoto": "/assets/trainer-headshots/Tristan Gray TC 360_x_360_.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Durham, NH | Tristan Gray | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Tristan Gray in Durham, NH, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "lorenzo-miller",
    "slug": "lorenzo-miller",
    "pageSlug": "lorenzomiller",
    "name": "Lorenzo Miller",
    "state": "Ohio",
    "market": "Cleveland, OH",
    "serviceArea": "Cleveland and surrounding Ohio communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Founder Lorenzo Miller built LDTT from childhood passion, professional study, and a mission of Serious Training. Serious Results.",
    "fullBio": "Lorenzo Miller Lorenzo’s love of dogs began at an early age. Growing up in the inner city at 6 years old, his heart went out to all the stray dogs in the neighborhood. He would see them knocking over garbage cans looking for food. He began to bring the dogs home but was not allowed to keep them. He smuggled them into his bedroom and trained them, knowing they had to be quiet in order to keep them hidden. Once his parents realized this was more than a phase, at age 10 they sent him off to train with various professional dog trainers. Lorenzo paid his way through college by providing in-home dog training. The Lorenzo’s training technique was developed after working with numerous dog trainers in the late 70’s and 80’s by studying different methods in various fields of training. Becoming frustrated with their weaknesses, Lorenzo took the best that each technique had to offer and developed his own style of training. Since its incorporation in 1987, Lorenzo’s Dog Training Team is responsible for the training of thousands of dogs and trainers in the Cleveland area. He is now placing trainers all over the world by recruiting, boarding, training, and hiring qualifying candidates to spread the Lorenzo’s technique and philosophy into the homes and businesses of dog owners around the world. Lorenzo’s motto has always been “Serious Training, Serious Results” with the main goal of keeping dogs in happy homes and out of shelters.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/lorenzo-miller",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/lorenzo-miller.jpg",
    "photo": "/assets/trainer-bio-photos/lorenzo-miller.jpg",
    "cardPhoto": "/assets/trainer-headshots/Lorenzo-Miller 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Cleveland, OH | Lorenzo Miller | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Lorenzo Miller in Cleveland, OH, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "eric-beck",
    "slug": "eric-beck",
    "pageSlug": "ericbeck",
    "name": "Eric Beck",
    "state": "Ohio",
    "market": "Cleveland, OH",
    "serviceArea": "Cleveland and surrounding Ohio communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Eric leads Beckin' Call Dog Training under LDTT's proven methods and standards for personalized, serious training results.",
    "fullBio": "Eric Beck Mentor, Ohio Experience the power of effective dog training with Beckin' Call Dog Training, your trusted partner for achieving real results. As an independent contractor operating under the umbrella of Lorenzo's Dog Training Team, we leverage their proven methods and expertise to deliver personalized training solutions. Our team is trained and certified by Lorenzo's renowned program, ensuring we meet the highest standards of quality and effectiveness. Serious Training, Serious Results.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/eric-beck",
    "layout": "mock-5",
    "pageStatus": "Published",
    "locked": true,
    "clicks": 1248,
    "forms": 67,
    "conversions": 9,
    "image": "/assets/trainer-bio-photos/eric-beck.jpg",
    "photo": "/assets/trainer-bio-photos/eric-beck.jpg",
    "cardPhoto": "/assets/trainer-headshots/Eric Beck TC 2 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Cleveland, OH | Eric Beck | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Eric Beck in Cleveland, OH, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "harley-mcgrew",
    "slug": "harley-mcgrew",
    "pageSlug": "harleymcgrew",
    "name": "Harley McGrew",
    "state": "Ohio",
    "market": "Cleveland Heights, OH",
    "serviceArea": "Cleveland Heights and surrounding Ohio communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Harley began as an LDTT client and now focuses on misunderstood dogs, large breeds, and aggression-related behavior challenges.",
    "fullBio": "Harley McGrew was born in Toledo, Ohio, raised in Oak Harbor, Ohio, and currently resides in Cleveland Heights, Ohio. Growing up with a lifelong love for dogs, Harley developed a passion for understanding canine behavior and helping dogs become successful members of their families and communities. Harley's journey with Lorenzo's Dog Training Team began as a client. After experiencing multiple unsuccessful attempts with traditional pet store training programs and facing challenges with a dog that was ultimately removed from a daycare program, Harley knew a different approach was needed. Encouraged by a family friend who had previously worked with Lorenzo's Dog Training Team, Harley enrolled as a client and quickly experienced firsthand the effectiveness of the training philosophy. What stood out most was the hands-on nature of the program and the emphasis on involving owners throughout the training process. Inspired by the results and the opportunity to make a meaningful difference in the lives of dogs and their families, Harley decided to pursue a career in professional dog training with Lorenzo's Dog Training Team. Harley's mission as a trainer is centered on helping dogs that are often misunderstood, particularly large breeds and dogs struggling with aggression-related behaviors. Harley is passionate about giving these dogs the structure, guidance, and opportunities they need to succeed while helping owners build safe, confident, and lasting relationships with their pets. Additionally, Harley hopes to play a role in helping long-term shelter dogs find stable, loving homes where they can thrive. When not working with dogs, Harley enjoys spending time outdoors and visiting the park with personal dogs. This everyday connection with dogs continues to fuel a passion for training and reinforces the belief that every dog deserves the opportunity to live a balanced and fulfilling life. Through dedication, personal experience, and a genuine commitment to helping both dogs and their owners succeed, Harley is proud to be part of Lorenzo's Dog Training Team and looks forward to creating lasting transformations for families and their canine companions.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/harley-mcgrew",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/harley-mcgrew.jpg",
    "photo": "/assets/trainer-bio-photos/harley-mcgrew.jpg",
    "cardPhoto": "/assets/trainer-headshots/Harley McGrew 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Cleveland Heights, OH | Harley McGrew | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Harley McGrew in Cleveland Heights, OH, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "john-delbane",
    "slug": "john-delbane",
    "pageSlug": "johndelbane",
    "name": "John (JD) DelBane",
    "state": "Ohio",
    "market": "Cleveland, OH",
    "serviceArea": "Cleveland and surrounding Ohio communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "JD is a Master Trainer with more than 700 dogs trained and experience in obedience, behavior, retrieval, scent, protection, therapy, and service work.",
    "fullBio": "John Delbane John DelBane got interested in professional dog training after meeting Lorenzo over 20 years ago. He was having behavioral issues with his first personal dog and contacted Lorenzo's Dog Training Team for help. From the first initial meeting, John grew interested in professional dog training. It wasn’t until many years later that John contacted Lorenzo with his current Rottweiler, Tonka. After going through training, he talked to Lorenzo about joining the team. Today, John has trained over 700 dogs over the last 10 years, and is currently a Master Trainer with the company. John spends time not only training dogs, but also working with new trainers to help them build their markets in Cleveland, Phoenix, Las Vegas, Dallas, and Oklahoma City. John was born in Ohio and grew up in Kansas. He currently resides in Mayfield, Ohio with his wife, Chrissy, and young son, CJ. John also shares his home with his Rottweiler, Tonka, and his therapy dog, Lola, a Douge De Bordeaux. John enjoys outdoor activities and sporting events with his family. His goals are to help clients have better relationships with their pets. He is able to enjoy a career that he loves, working with animals and people. Not only does John work with clients and their dogs with behavioral issues and basic obedience, he’s also certified in specialized training that includes retrieval, scent work, and various levels of protection training. John has continued his own training, education, and personal growth so that he is now qualified and experienced in training therapy and service dogs, which he finds deeply rewarding.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/john-delbane",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/john-delbane.jpg",
    "photo": "/assets/trainer-bio-photos/john-delbane.jpg",
    "cardPhoto": "/assets/trainer-headshots/John Delbane.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Cleveland, OH | John (JD) DelBane | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with John (JD) DelBane in Cleveland, OH, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "shannon-paskins",
    "slug": "shannon-paskins",
    "pageSlug": "shannonpaskins",
    "name": "Shannon Paskins",
    "state": "Ohio",
    "market": "Reynoldsburg, OH",
    "serviceArea": "Reynoldsburg and surrounding Ohio communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Shannon's no-kill shelter experience drives her mission to help dogs overcome obstacles and help families build better communication.",
    "fullBio": "Shannon Paskins is a dog trainer with Lorenzo’s Dog Training Team, serving clients throughout Fairfield County and the surrounding Central Ohio area. She currently resides in Reynoldsburg, Ohio, and brings a deep compassion for dogs and their families into every training relationship. Shannon’s journey into dog training began through her hands-on experience working with dogs in a no-kill animal shelter, where she saw firsthand how behavioral challenges can prevent great dogs from finding homes. Some dogs remained in the shelter for years due to a lack of training resources, often requiring staff members to foster or seek outside assistance. Wanting to be part of the solution, Shannon pursued the opportunity to train with Lorenzo’s Dog Training Team so she could help dogs overcome obstacles and improve their chances of success—both in shelters and in family homes. While she does not come from a formal education background in animal behavior, Shannon has spent her entire life around dogs and cats, giving her a strong understanding of how deeply pets are woven into family life—and how challenging that responsibility can sometimes be. Her experience working with shelter dogs, as well as caring for boarded dogs, has allowed her to develop valuable skills in handling a wide range of temperaments while also building strong relationships with pet owners. Shannon is driven by the goal of providing a secure, enriching life for both her pets and the dogs she works with. She is passionate about helping families create balanced, structured environments where dogs can thrive physically and mentally. Outside of dog training, Shannon enjoys playing video games with friends, reading, writing, baking, and even blacksmithing, bringing creativity and patience into all aspects of her life—including her work with dogs. With empathy, real-world experience, and a strong commitment to helping dogs succeed, Shannon is proud to be part of Lorenzo’s Dog Training Team and to support families in building clearer communication and stronger bonds with their canine companions.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/shannon-paskins",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/shannon-paskins.jpg",
    "photo": "/assets/trainer-bio-photos/shannon-paskins.jpg",
    "cardPhoto": "/assets/trainer-headshots/Shannon Paskins TT 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Reynoldsburg, OH | Shannon Paskins | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Shannon Paskins in Reynoldsburg, OH, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "brady-deremer",
    "slug": "brady-deremer",
    "pageSlug": "bradyderemer",
    "name": "Brady DeRemer",
    "state": "Ohio",
    "market": "Streetsboro, OH",
    "serviceArea": "Streetsboro, Cleveland, Akron, and surrounding Ohio communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Brady is a Lorenzo's Certified Dog Trainer serving Streetsboro and surrounding Ohio communities with obedience training and behavior modification support.",
    "fullBio": "Brady DeRemer is a Lorenzo's Certified Dog Trainer serving Streetsboro, Ohio and the surrounding communities. His trainer profile has been published through Lorenzo's office so families can request training support directly through the approved Lorenzo's Dog Training Team process. Brady works under Lorenzo's proven system with a focus on dependable obedience, behavior modification, owner leadership, and real-world results. His trainer landing page routes each request through Lorenzo's production office so the team can track the inquiry, follow up properly, and connect the family with the right next step. A full expanded bio can be added by the office once Brady's final approved story is ready. In the meantime, this page gives clients a clean profile, confirms his service area, and keeps the schedule-this-trainer flow connected to his active landing page.",
    "sourceBioUrl": "",
    "layout": "mock-5",
    "pageStatus": "Published",
    "locked": true,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "https://ptnzaeprvkgjgtupmcty.supabase.co/storage/v1/object/public/trainer-page-assets/15580a72-b9dc-4220-8975-677bbabb3902/landingBioPhoto-1785523213042.jpg",
    "photo": "https://ptnzaeprvkgjgtupmcty.supabase.co/storage/v1/object/public/trainer-page-assets/15580a72-b9dc-4220-8975-677bbabb3902/landingBioPhoto-1785523213042.jpg",
    "cardPhoto": "https://ptnzaeprvkgjgtupmcty.supabase.co/storage/v1/object/public/trainer-page-assets/15580a72-b9dc-4220-8975-677bbabb3902/profilePhoto-1785347165713.jpg",
    "landingBioPhoto": "https://ptnzaeprvkgjgtupmcty.supabase.co/storage/v1/object/public/trainer-page-assets/15580a72-b9dc-4220-8975-677bbabb3902/landingBioPhoto-1785523213042.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Streetsboro, OH | Brady DeRemer | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Brady DeRemer in Streetsboro, OH, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "karemela-sefferin",
    "slug": "karemela-sefferin",
    "pageSlug": "karemelasefferin",
    "name": "Karemela Sefferin",
    "state": "California",
    "market": "San Diego, CA",
    "serviceArea": "San Diego and surrounding California communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Karemela helps families build trust, improve communication, and create lasting relationships between dogs and their owners.",
    "fullBio": "Born, raised, and currently living in San Diego, California, Karemela Sefferin has always been driven by one simple goal: to make life better for every person and animal she encounters. That passion for helping others naturally led her to the world of professional dog training. Karemela's journey began with her own dog, Jazzie, a 10-year-old Shepherd-Pit Bull mix who struggled with reactivity toward people, dogs, bicycles, and skateboards. After trying numerous training methods on her own, she reached a point where progress had stalled. A close friend who had become a trainer with Lorenzo's Dog Training Team recommended she schedule an evaluation. The transformation she witnessed was immediate and remarkable. Jazzie became more engaged, attentive, and responsive without relying on treats, creating a stronger bond between them than Karemela ever thought possible. That life-changing experience inspired her to help other families build the same trusting relationship with their dogs. Service has always been at the heart of Karemela's life. Growing up, she watched her mother dedicate herself to caring for elderly individuals and later assisting children with special needs in the classroom. Those experiences instilled in her the values of patience, compassion, and selfless service. Karemela has spent much of her career in customer service and caregiving, including working with elderly individuals living with Alzheimer's disease while pursuing a nursing degree. Her background has strengthened her ability to communicate, educate, and support people through challenging situations—skills that translate naturally into coaching both dogs and their owners. Today, Karemela combines her lifelong passion for helping others with her love of dogs. She believes successful training isn't just about teaching obedience—it's about building trust, improving communication, and creating lasting relationships between dogs and their families. Outside of training, Karemela enjoys scenic walks throughout San Diego and spending her free time working on creative personal projects. Her mission remains the same in everything she does: to leave every person and every animal better than she found them.",
    "sourceBioUrl": "",
    "layout": "mock-5",
    "pageStatus": "Published",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/karemela-sefferin-candid.jpg",
    "photo": "/assets/trainer-bio-photos/karemela-sefferin-candid.jpg",
    "cardPhoto": "/assets/trainer-headshots/Karemela Sefferin 360_x_360.jpg",
    "heroTrainerPhoto": "/assets/trainer-bio-photos/karemela-sefferin-candid.jpg",
    "landingBioPhoto": "/assets/trainer-bio-photos/karemela-sefferin-candid.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in San Diego, CA | Karemela Sefferin | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Karemela Sefferin in San Diego, CA, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "jacob-perez",
    "slug": "jacob-perez",
    "pageSlug": "jacobperez",
    "name": "Jacob Perez",
    "state": "Texas",
    "market": "San Antonio, TX",
    "serviceArea": "San Antonio and surrounding Texas communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Jacob brings Marine Corps discipline, sports medicine, personal training, and dog-industry experience into his LDTT work.",
    "fullBio": "Jacob Perez I was born and raised in the San Antonio area and later spent 15 years building a life in San Diego. Growing up in the small town of Lytle, I developed a deep connection with dogs at an early age. My father’s ranch was home to several stray dogs, and as a kid, I naturally gravitated toward them. By feeding them, caring for them, and earning their trust, I found some of my earliest and most loyal friendships. Looking back, that’s where my passion for dogs truly began. At 18, I answered the call to serve and joined the United States Marine Corps. I spent six years on active duty before continuing my service in the reserves. The Marine Corps taught me discipline, leadership, accountability, and the value of working as part of a high-performing team. Those qualities continue to shape every aspect of my life today. In 2016, I was accepted into San Diego State University, where I earned a degree in Sports Medicine. I also became a certified personal trainer, building a career focused on health, performance, and helping others reach their potential. But despite my passion for fitness, I found myself increasingly drawn toward working with dogs. My military experience alongside canine handlers, my time working in the pet industry, and most importantly, raising and training my first American Bully, Carrot, all pointed me in the same direction. Watching my own dog transform through consistent training was incredibly rewarding. The bond we built and the progress we achieved sparked something in me… It made me realize that I wanted to help other owners experience that same sense of pride, confidence, and connection with their dogs. After working with several training companies, a friend introduced me to Lorenzo’s Dog Training Team. From the moment I experienced their approach, I knew I had found the right place. The professionalism, standards, and results stood apart from anything I had seen before. Today, my goal is to continue growing into a Master Trainer and to learn from some of the best professionals in the industry. I thrive in team environments and enjoy mentoring and supporting fellow trainers across the country. There is nothing more rewarding than helping people strengthen their relationship with their dogs and watching both owner and dog gain confidence together. Outside of work, you’ll usually find me training in martial arts, riding my motorcycle, or spending time with my dogs. Above all, I value family. No matter where life takes me, the time I spend with the people and dogs I care about most is what keeps me grounded.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/jacob-perez",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/jacob-perez.jpg",
    "photo": "/assets/trainer-bio-photos/jacob-perez.jpg",
    "cardPhoto": "/assets/trainer-headshots/Jacob Perez_TC 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in San Antonio, TX | Jacob Perez | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Jacob Perez in San Antonio, TX, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "eric-hardaway",
    "slug": "eric-hardaway",
    "pageSlug": "erichardaway",
    "name": "Eric Hardaway",
    "state": "Texas",
    "market": "Fort Worth, TX",
    "serviceArea": "Fort Worth and surrounding Texas communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Eric's psychology background, wildlife work, and experience training his own German Shepherd led him to serve the Dallas/Fort Worth area.",
    "fullBio": "Eric Hardaway FORT WORTH, TX Eric was born and raised around the Eagle Mountain Lake area of Fort Worth, Texas. He attended and graduated high school at Marine Military Academy in Harlingen, Texas before heading to Texas Tech University to further his education and to graduate with a degree in Psychology. After earning his degree, he began a career as a Wildlife Specialist with Critter Control helping to protect animals from people, and people from animals. At this time, his best friend and business partner, Bacon, came into his life. Bacon, a rescued German Shepherd, needed training so Eric spoke with his veterinarian who recommended Lorenzo’s Dog Training Team and their team trainer Matthew Watson. Working together with Matthew, Eric was passionate about learning how to train his dog, and he kept asking his trainer to teach him more training techniques. Matthew embraced the desire of his client by inviting Eric to join the team, and the rest is history. Today, Eric and Bacon can be found around the Dallas/Fort Worth Metroplex looking for and helping dogs and their owners every chance they get. Eric’s love of animals and his dedication to keeping dogs out of shelters is evident when you meet him. He is very proud to be a part of Lorenzo’s Dog Training Team, and he encourages you to call if you need any assistance with your dog.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/eric-hardaway",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/eric-hardaway.jpg",
    "photo": "/assets/trainer-bio-photos/eric-hardaway.jpg",
    "cardPhoto": "/assets/trainer-headshots/Eric-Hardaway-360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in Fort Worth, TX | Eric Hardaway | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Eric Hardaway in Fort Worth, TX, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  },
  {
    "id": "carolina-perez",
    "slug": "carolina-perez",
    "pageSlug": "carolinaperez",
    "name": "Carolina Perez",
    "state": "Texas",
    "market": "San Antonio, TX",
    "serviceArea": "San Antonio and surrounding Texas communities",
    "phone": "(866) 436-4959",
    "email": "",
    "username": "",
    "title": "Lorenzo's Certified Dog Trainer",
    "tagline": "Serious training for real-life results.",
    "heroHeadline": "The right trainer. The right results.",
    "bio": "Carolina combines sales, personal training, and a love for animals to help dogs and families live together more happily.",
    "fullBio": "Carolina Perez SAN ANTONIO, TEXAS Carolina was born and raised in San Diego, California and currently resides in Texas. Between her love for working with animals and her experience with the public in sales and being a personal trainer (for humans), it was only natural that she would eventually merge the two to become a dog trainer with LDTT. “I wanted to become a dog trainer because I truly love working with animals. And I think it’s amazing to see the work that’s put in when you see the dog you trained, working. I wanted to be a part of LDTT because I want to work with people who love animals and love helping animals as much as I do.” Her goal is simply to help dogs and their families live together happily. When Carolina isn’t working on that goal, she enjoys going for walks, hiking, working out, going to the beach, and spending time with her family.",
    "sourceBioUrl": "https://www.lorenzosdogtrainingteam.com/carolina-perez",
    "layout": "mock-5",
    "pageStatus": "No Site Started",
    "locked": false,
    "clicks": 0,
    "forms": 0,
    "conversions": 0,
    "image": "/assets/trainer-bio-photos/carolina-perez.jpg",
    "photo": "/assets/trainer-bio-photos/carolina-perez.jpg",
    "cardPhoto": "/assets/trainer-headshots/Carolina Perez tc 360_x_360.jpg",
    "companyLogo": "",
    "specialties": [
      "Dog Obedience Training",
      "Behavior Modification",
      "Puppy Training",
      "Real-World Owner Leadership"
    ],
    "credentials": [
      "Lorenzo's Certified Dog Trainer",
      "Powered by Lorenzo's Dog Training Team",
      "Office-managed lead follow-up"
    ],
    "seoTitle": "Dog Trainer in San Antonio, TX | Carolina Perez | Lorenzo's Dog Training Team",
    "seoDescription": "Professional dog obedience training and behavior modification with Carolina Perez in San Antonio, TX, backed by Lorenzo's Dog Training Team.",
    "review1Author": "Local Client",
    "review1Copy": "Professional, patient, and focused on training that works in everyday life.",
    "review2Author": "Dog Owner",
    "review2Copy": "The office follow-up was clear, and the training plan gave our family a practical path forward.",
    "review3Author": "Verified Client",
    "review3Copy": "Better communication, calmer behavior, and results we could see at home and in public.",
    "socials": {
      "facebook": "",
      "instagram": "",
      "tiktok": ""
    }
  }
];
